# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datadash < Formula
  desc "Visualize and graph streaming data in the terminal"
  homepage "https://github.com/keithknott26/datadash"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_darwin_amd64.tar.gz"
      sha256 "664693d305ce19cf877f5d7764ab8d2ea1d77bb9727c933b440a1e4d9e5e12f4"

      define_method(:install) do
        bin.install "datadash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_darwin_arm64.tar.gz"
      sha256 "532bb3b8c79c4cec307e2bfcc48fd958db9458b98b4cd639c1fbdd337493fe86"

      define_method(:install) do
        bin.install "datadash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_linux_amd64.tar.gz"
      sha256 "ebc8d2cd793b33d2690d117548ad77aebb10c62d1b272db869722ea20d6ffa7a"
      define_method(:install) do
        bin.install "datadash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_linux_arm64.tar.gz"
      sha256 "9a8e48620cd86ef0481a4d4b577d22eb967ff926e0230e6c308a8f6c0eee669f"
      define_method(:install) do
        bin.install "datadash"
      end
    end
  end

  test do
    system "#{bin}/datadash", "--version"
  end
end
