# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datadash < Formula
  desc "Visualize and graph streaming data in the terminal"
  homepage "https://github.com/keithknott26/datadash"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_darwin_amd64.tar.gz"
      sha256 "32ed5ebd0381c2bdf37ec5201ef750d9cf3f7bb958458b718595724a36c0678a"

      define_method(:install) do
        bin.install "datadash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_darwin_arm64.tar.gz"
      sha256 "2cfaf0525cf7a235b4c23f49992f40f73985def48191b089ec515e267c152856"

      define_method(:install) do
        bin.install "datadash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_linux_amd64.tar.gz"
      sha256 "d0708c34a3ee2b6e168744cf6e9e4d2af2ed049fa230c35209b1a6de8bc2d863"
      define_method(:install) do
        bin.install "datadash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_linux_arm64.tar.gz"
      sha256 "c3617cde2a31837783c200b33ab356835f19b0f137f442b62f6d3f08d3461a0b"
      define_method(:install) do
        bin.install "datadash"
      end
    end
  end

  test do
    system "#{bin}/datadash", "--version"
  end
end
