# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datadash < Formula
  desc "Visualize and graph streaming data in the terminal"
  homepage "https://github.com/keithknott26/datadash"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_darwin_amd64.tar.gz"
      sha256 "41c26c06c84ceffe67ea9ad7d38232224f346de057ba9372f4006ae2de632bbf"

      define_method(:install) do
        bin.install "datadash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_darwin_arm64.tar.gz"
      sha256 "44646bbc870d32815035b2fa2b3afb54fefae03b4b12b6774637011b908bcd04"

      define_method(:install) do
        bin.install "datadash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_linux_amd64.tar.gz"
      sha256 "332365df83874477c901832e23414d850ad233efef9c6b25e630cf62658b53c8"
      define_method(:install) do
        bin.install "datadash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keithknott26/datadash/releases/download/v0.5.1/datadash_0.5.1_linux_arm64.tar.gz"
      sha256 "15f350b6baa714ceb2038605d87d090d2ca7b8581ee146de7fef6a6664b34553"
      define_method(:install) do
        bin.install "datadash"
      end
    end
  end

  test do
    system "#{bin}/datadash", "--version"
  end
end
